# Generated by Django 5.2.5 on 2025-08-22 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ratings',
            field=models.PositiveBigIntegerField(default=1, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(5)]),
            preserve_default=False,
        ),
    ]
