# Generated by Django 5.2.5 on 2025-08-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_review_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='commet',
        ),
    ]
