# Generated by Django 5.2.5 on 2025-08-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_review_date_review_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='commet',
            new_name='comment',
        ),
    ]
