# Generated by Django 5.2.5 on 2025-08-25 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_review_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
