# Generated by Django 5.2.5 on 2025-08-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_quantity_cartitem_qunatity_alter_cart_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
